# Generated by Django 4.2.6 on 2023-12-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='data',
            new_name='date',
        ),
    ]
